---
# master node: prepare
- hosts: agent-nodes
  vars_files:
    - "common_vars.yml"
  roles:
    - role: clean
    - role: prepare

# etcd node setting
- hosts: etcd
  vars_files:
    - "common_vars.yml"
  roles:
    - role: etcd

# master nodes setting
- hosts: master-nodes
  vars_files:
    - "common_vars.yml"
  roles:
    - role: master

# agent nodes setting
- hosts: agent-nodes
  vars_files:
    - "common_vars.yml"
  roles:  
    - role: flannel 
    - role: docker
    - role: node
...
