version: '2'

services:
  # Elasticsearch service
  kibana:
    image: kibana:7.3.0
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: "no"
